name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: ./back

    - name: Build (if needed)
      run: echo "No build step necessary"
      working-directory: ./back

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: BackEndFullStack  # ← assure-toi que c’est bien le nom exact dans Azure
        slot-name: production
        package: ./back
